// Shared shading-model macro setup for material and deferred passes.
#ifndef BURT_SHADING_MODEL_MACROS_INCLUDED
#define BURT_SHADING_MODEL_MACROS_INCLUDED

#if !defined(BURT_MATERIAL_SHADING_MODEL_DEFAULT_LIT) && !defined(BURT_MATERIAL_SHADING_MODEL_HAIR) && !defined(BURT_MATERIAL_SHADING_MODEL_CLEAR_COAT) && !defined(BURT_MATERIAL_SHADING_MODEL_SUBSURFACE) && !defined(BURT_MATERIAL_SHADING_MODEL_FABRIC) && !defined(BURT_MATERIAL_SHADING_MODEL_SILK)
    #define BURT_MATERIAL_SHADING_MODEL_DEFAULT_LIT 1
#endif

#if defined(BURT_MATERIAL_SHADING_MODEL_HAIR)
    #define BURT_MATERIAL_SELECTED_SHADING_MODEL_HAIR 1
#elif defined(BURT_MATERIAL_SHADING_MODEL_CLEAR_COAT)
    #define BURT_MATERIAL_SELECTED_SHADING_MODEL_CLEAR_COAT 1
#elif defined(BURT_MATERIAL_SHADING_MODEL_SUBSURFACE)
    #define BURT_MATERIAL_SELECTED_SHADING_MODEL_SUBSURFACE 1
#elif defined(BURT_MATERIAL_SHADING_MODEL_FABRIC)
    #define BURT_MATERIAL_SELECTED_SHADING_MODEL_FABRIC 1
#elif defined(BURT_MATERIAL_SHADING_MODEL_SILK)
    #define BURT_MATERIAL_SELECTED_SHADING_MODEL_FABRIC 1
    #define BURT_MATERIAL_SELECTED_FABRIC_IS_SILK 1
#else
    #define BURT_MATERIAL_SELECTED_SHADING_MODEL_DEFAULT_LIT 1
#endif

#if defined(BURT_FORWARD_SINGLE_SHADING_MODEL) || defined(BURT_MATERIAL_GBUFFER_SINGLE_SHADING_MODEL)
    #define BURT_MATERIAL_SINGLE_SHADING_MODEL 1
#endif

#if defined(BURT_MATERIAL_SINGLE_SHADING_MODEL) || defined(BURT_DEFERRED_LIGHTING_SINGLE_SHADING_MODEL)
    #define BURT_STATIC_SHADING_MODEL 1
#else
    #define BURT_STATIC_SHADING_MODEL 0
#endif

#if defined(BURT_MATERIAL_SINGLE_SHADING_MODEL)
    #if defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_HAIR)
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 1
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 0
    #elif defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_CLEAR_COAT)
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 1
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 0
    #elif defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_SUBSURFACE)
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 1
        #define BURT_ENABLE_FABRIC_SHADING 0
    #elif defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_FABRIC)
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 1
    #else
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 1
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 0
    #endif
#endif

#if defined(BURT_DEFERRED_LIGHTING_SINGLE_SHADING_MODEL)
    #if defined(BURT_DEFERRED_SHADING_MODEL_HAIR)
        #define BURT_DEFERRED_LIGHTING_SHADING_MODEL_ID BURT_SHADING_MODEL_HAIR
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 1
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 0
    #elif defined(BURT_DEFERRED_SHADING_MODEL_CLEAR_COAT)
        #define BURT_DEFERRED_LIGHTING_SHADING_MODEL_ID BURT_SHADING_MODEL_CLEAR_COAT
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 1
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 0
    #elif defined(BURT_DEFERRED_SHADING_MODEL_SUBSURFACE)
        #define BURT_DEFERRED_LIGHTING_SHADING_MODEL_ID BURT_SHADING_MODEL_SUBSURFACE
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 1
        #define BURT_ENABLE_FABRIC_SHADING 0
    #elif defined(BURT_DEFERRED_SHADING_MODEL_FABRIC)
        #define BURT_DEFERRED_LIGHTING_SHADING_MODEL_ID BURT_SHADING_MODEL_FABRIC
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 1
    #else
        #define BURT_DEFERRED_LIGHTING_SHADING_MODEL_ID BURT_SHADING_MODEL_DEFAULT_LIT
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 1
        #define BURT_ENABLE_HAIR_SHADING 0
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
        #define BURT_ENABLE_FABRIC_SHADING 0
    #endif
#endif

#if !defined(BURT_ENABLE_DEFAULT_LIT_SHADING)
    #if defined(BURT_DEFERRED_LIGHTING_SINGLE_SHADING_MODEL) || defined(BURT_MATERIAL_SINGLE_SHADING_MODEL)
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 0
    #else
        #define BURT_ENABLE_DEFAULT_LIT_SHADING 1
    #endif
#endif

#if !defined(BURT_ENABLE_HAIR_SHADING)
    #if defined(BURT_DEFERRED_LIGHTING_SINGLE_SHADING_MODEL) || defined(BURT_MATERIAL_SINGLE_SHADING_MODEL)
        #define BURT_ENABLE_HAIR_SHADING 0
    #else
        #define BURT_ENABLE_HAIR_SHADING 1
    #endif
#endif

#if !defined(BURT_ENABLE_CLEAR_COAT_SHADING)
    #if defined(BURT_DEFERRED_LIGHTING_SINGLE_SHADING_MODEL) || defined(BURT_MATERIAL_SINGLE_SHADING_MODEL)
        #define BURT_ENABLE_CLEAR_COAT_SHADING 0
    #else
        #define BURT_ENABLE_CLEAR_COAT_SHADING 1
    #endif
#endif

#if !defined(BURT_ENABLE_SUBSURFACE_SHADING)
    #if defined(BURT_DEFERRED_LIGHTING_SINGLE_SHADING_MODEL) || defined(BURT_MATERIAL_SINGLE_SHADING_MODEL)
        #define BURT_ENABLE_SUBSURFACE_SHADING 0
    #else
        #define BURT_ENABLE_SUBSURFACE_SHADING 1
    #endif
#endif

#if !defined(BURT_ENABLE_FABRIC_SHADING)
    #if defined(BURT_DEFERRED_LIGHTING_SINGLE_SHADING_MODEL) || defined(BURT_MATERIAL_SINGLE_SHADING_MODEL)
        #define BURT_ENABLE_FABRIC_SHADING 0
    #else
        #define BURT_ENABLE_FABRIC_SHADING 1
    #endif
#endif

#if BURT_STATIC_SHADING_MODEL
    #if defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_DEFAULT_LIT) || defined(BURT_DEFERRED_SHADING_MODEL_DEFAULT_LIT)
        #define BURT_ACTIVE_DEFAULT_LIT_SHADING_MODEL 1
    #else
        #define BURT_ACTIVE_DEFAULT_LIT_SHADING_MODEL 0
    #endif

    #if defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_HAIR) || defined(BURT_DEFERRED_SHADING_MODEL_HAIR)
        #define BURT_ACTIVE_HAIR_SHADING_MODEL 1
    #else
        #define BURT_ACTIVE_HAIR_SHADING_MODEL 0
    #endif

    #if defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_CLEAR_COAT) || defined(BURT_DEFERRED_SHADING_MODEL_CLEAR_COAT)
        #define BURT_ACTIVE_CLEAR_COAT_SHADING_MODEL 1
    #else
        #define BURT_ACTIVE_CLEAR_COAT_SHADING_MODEL 0
    #endif

    #if defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_SUBSURFACE) || defined(BURT_DEFERRED_SHADING_MODEL_SUBSURFACE)
        #define BURT_ACTIVE_SUBSURFACE_SHADING_MODEL 1
    #else
        #define BURT_ACTIVE_SUBSURFACE_SHADING_MODEL 0
    #endif

    #if defined(BURT_MATERIAL_SELECTED_SHADING_MODEL_FABRIC) || defined(BURT_DEFERRED_SHADING_MODEL_FABRIC)
        #define BURT_ACTIVE_FABRIC_SHADING_MODEL 1
    #else
        #define BURT_ACTIVE_FABRIC_SHADING_MODEL 0
    #endif
#else
    #define BURT_ACTIVE_DEFAULT_LIT_SHADING_MODEL 0
    #define BURT_ACTIVE_HAIR_SHADING_MODEL 0
    #define BURT_ACTIVE_CLEAR_COAT_SHADING_MODEL 0
    #define BURT_ACTIVE_SUBSURFACE_SHADING_MODEL 0
    #define BURT_ACTIVE_FABRIC_SHADING_MODEL 0
#endif

bool BurtIsActiveDefaultLitShadingModel(float shadingModelID)
{
#if BURT_STATIC_SHADING_MODEL
    #if BURT_ACTIVE_DEFAULT_LIT_SHADING_MODEL
        return true;
    #else
        return false;
    #endif
#else
    return abs(BurtResolveSurfaceShadingModel(shadingModelID) - BURT_SHADING_MODEL_DEFAULT_LIT) < 0.5f;
#endif
}

bool BurtIsActiveHairShadingModel(float shadingModelID)
{
#if BURT_STATIC_SHADING_MODEL
    #if BURT_ACTIVE_HAIR_SHADING_MODEL
        return true;
    #else
        return false;
    #endif
#else
    return BurtIsHairShadingModel(shadingModelID);
#endif
}

bool BurtIsActiveClearCoatShadingModel(float shadingModelID)
{
#if BURT_STATIC_SHADING_MODEL
    #if BURT_ACTIVE_CLEAR_COAT_SHADING_MODEL
        return true;
    #else
        return false;
    #endif
#else
    return BurtIsClearCoatShadingModel(shadingModelID);
#endif
}

bool BurtIsActiveSubsurfaceShadingModel(float shadingModelID)
{
#if BURT_STATIC_SHADING_MODEL
    #if BURT_ACTIVE_SUBSURFACE_SHADING_MODEL
        return true;
    #else
        return false;
    #endif
#else
    return BurtIsSubsurfaceShadingModel(shadingModelID);
#endif
}

bool BurtIsActiveFabricShadingModel(float shadingModelID)
{
#if BURT_STATIC_SHADING_MODEL
    #if BURT_ACTIVE_FABRIC_SHADING_MODEL
        return true;
    #else
        return false;
    #endif
#else
    return BurtIsFabricShadingModel(shadingModelID);
#endif
}

#endif // BURT_SHADING_MODEL_MACROS_INCLUDED
