#if BURT_EXPOSURE_VALIDATION
using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Text;using System.Reflection;using UnityEngine;using UnityEngine.Rendering;using Burt.RenderPipeline;

public static class BurtExposurePlayerValidation{
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Boot(){if(!Application.isEditor && Environment.GetCommandLineArgs().Contains("--brp-exposure-validation")){new GameObject("Exposure validation driver").AddComponent<BurtExposureValidationDriver>();}}
 public static void Heartbeat(){RenderPipelineManager.endCameraRendering-=End;RenderPipelineManager.endCameraRendering+=End;}
 class Test{public string name;public float ev,comp,cal=1,elevation=25;public ExposureMode mode=ExposureMode.ManualEV100;public float iso=100,seconds;public bool taa,off,clamp,skyOnly,blackClear,noCull,noJitter;public int effects=3;}
 static Color originalClear;static bool boundaries;static bool parity;static float savedCaptureDelta;
 public static string StartParity(){parity=true;return Start();}
 static bool isolateParity,diagnostics;public static string StartIsolateParity(){isolateParity=true;return Start();}public static string StartDiagnostics(){diagnostics=true;isolateParity=true;return Start();}
 static bool skyOnlyDiagnostic;public static string StartSkyOnly(){skyOnlyDiagnostic=true;diagnostics=true;isolateParity=true;return Start();}
 public static string StartBoundaries(){boundaries=true;return Start();}
 static bool isolation,longSettle;static int originalMask;static Renderer[] renderers;static bool[] rendererStates;
 public static string StartIsolation(){isolation=true;return Start();}
 public static string StartLongSettle(){longSettle=true;return Start();}
 static List<Test> tests=new List<Test>();static int path,step,age;static double start;static Camera cam;static Light sun;static Quaternion sunRot;static float lightIntensity;static Color lightColor;static bool bg;static Light[] lights;static bool[] states;
 static RenderTexture rt;static RenderPipelineAsset original;static BurtRenderPipelineAsset clone;static VolumeProfile profile;static List<VolumeComponent> added=new List<VolumeComponent>();static Dictionary<VolumeComponent,string> saved=new Dictionary<VolumeComponent,string>();static string cameraJson;static BurtCameraData cd;
 static AtmosphereVolumeComponent a;static VolumetricFogVolumeComponent v;static ExposureVolumeComponent e;static TonemappingVolumeComponent tone;static string dir;static StringBuilder csv=new StringBuilder("path,case,age,seconds,nonfinite,meanRGB,maxRGB,preExposure,currentScale,targetScale,sampleAge,rtCount,rtBytes\n");public static string Status="Idle";
 static T Component<T>()where T:VolumeComponent{if(!profile.TryGet<T>(out var c)){c=profile.Add<T>(true);added.Add(c);}else saved[c]=JsonUtility.ToJson(c);return c;}
 public static string Start(){if(!Application.isPlaying)throw new Exception("Play required");cam=Camera.main;if(!cam||cam.name!="Atmosphere Test Camera"||cam.targetTexture)throw new Exception("Test camera required");cd=cam.GetComponent<BurtCameraData>();cameraJson=JsonUtility.ToJson(cd);sun=RenderSettings.sun;sunRot=sun.transform.rotation;lightIntensity=sun.intensity;lightColor=sun.color;bg=Application.runInBackground;lights=UnityEngine.Object.FindObjectsOfType<Light>();states=lights.Select(l=>l.enabled).ToArray();foreach(var l in lights)if(l!=sun)l.enabled=false;
  originalClear=cd.ClearColor;originalMask=cam.cullingMask;renderers=UnityEngine.Object.FindObjectsOfType<Renderer>();rendererStates=renderers.Select(r=>r.enabled).ToArray();profile=GameObject.Find("Atmosphere Controls").GetComponent<Volume>().profile;a=Component<AtmosphereVolumeComponent>();v=Component<VolumetricFogVolumeComponent>();e=Component<ExposureVolumeComponent>();tone=Component<TonemappingVolumeComponent>();var fog=Component<FogVolumeComponent>();var shaft=Component<LightShaftVolumeComponent>();var local=Component<LocalExposureVolumeComponent>();
  a.enabled.Override(true);a.aerialPerspective.Override(true);a.moonEnabled.Override(false);a.starsEnabled.Override(false);a.panoramicCloudEnabled.Override(false);a.weatherSkyCoverageEnabled.Override(false);a.physicalSkyTimeOfDayCurve.Override(0);v.enabled.Override(true);fog.enabled.Override(false);shaft.enabled.Override(false);shaft.bloomEnabled.Override(false);local.enabled.Override(false);tone.enabled.Override(false);tone.mode.Override(TonemappingMode.None);
  Component<BloomVolumeComponent>().enabled.Override(false);
  original=QualitySettings.renderPipeline;clone=UnityEngine.Object.Instantiate((BurtRenderPipelineAsset)GraphicsSettings.currentRenderPipeline);clone.hideFlags=HideFlags.DontSave;clone.name="Atmosphere exposure temporary";QualitySettings.renderPipeline=clone;rt=new RenderTexture(640,360,24,RenderTextureFormat.ARGBHalf){name="Atmosphere exposure target"};rt.Create();cam.targetTexture=rt;Application.runInBackground=true;
  foreach(float ev in new[]{-4f,-1f,0f,1f,4f})tests.Add(new Test{name="manual"+ev,ev=ev});tests.Add(new Test{name="comp1",comp=1});tests.Add(new Test{name="cal-half",cal=.5f});float physicalEv=Mathf.Log(2.8f*2.8f*60,2);tests.Add(new Test{name="physical-reference",ev=physicalEv});tests.Add(new Test{name="physical100",mode=ExposureMode.PhysicalCamera});tests.Add(new Test{name="physical200",mode=ExposureMode.PhysicalCamera,iso=200});
  tests.Add(new Test{name="taa-minus4",ev=-4,taa=true});tests.Add(new Test{name="taa-plus4",ev=4,taa=true});tests.Add(new Test{name="taa-restore",taa=true});
  foreach(var mode in new[]{ExposureMode.Automatic,ExposureMode.AutomaticHistogram}){string p=mode==ExposureMode.Automatic?"average":"histogram";tests.Add(new Test{name=p+"-day",mode=mode,elevation=60,seconds=6});tests.Add(new Test{name=p+"-night",mode=mode,elevation=-18,seconds=6});tests.Add(new Test{name=p+"-dawn",mode=mode,elevation=2,seconds=6});tests.Add(new Test{name=p+"-clamp",mode=mode,elevation=-18,seconds=4,clamp=true});}
  tests.Add(new Test{name="cal-zero",cal=0});tests.Add(new Test{name="cal-zero-restore",cal=1});
  tests.Add(new Test{name="exposure-off",off=true});tests.Add(new Test{name="manual-restore"});
  if(isolation){tests.Clear();for(int fx=0;fx<4;fx++)foreach(float ev in new[]{0f,1f,4f})tests.Add(new Test{name="effects"+fx+"-ev"+ev,ev=ev,effects=fx});foreach(float ev in new[]{0f,1f,4f}){tests.Add(new Test{name="sky-no-geometry-ev"+ev,ev=ev,effects=1,skyOnly=true});tests.Add(new Test{name="sky-black-clear-ev"+ev,ev=ev,effects=1,skyOnly=true,blackClear=true});}}
  if(longSettle){tests.Clear();foreach(var mode in new[]{ExposureMode.Automatic,ExposureMode.AutomaticHistogram}){string p=mode.ToString();tests.Add(new Test{name=p+"-day",mode=mode,elevation=60,seconds=3});tests.Add(new Test{name=p+"-night15s",mode=mode,elevation=-18,seconds=15});}}
  if(boundaries){tests.Clear();foreach(int fx in new[]{0,1})tests.Add(new Test{name="solid-atmosphere"+fx,effects=fx,skyOnly=true,off=true});typeof(BurtCameraData).GetField("clearMode",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(cd,BurtCameraClearMode.SolidColor);}
  skyOnlyDiagnostic|=Environment.GetCommandLineArgs().Contains("--brp-exposure-sky-only");diagnostics|=skyOnlyDiagnostic||Environment.GetCommandLineArgs().Contains("--brp-exposure-diagnostics");isolateParity|=diagnostics||Environment.GetCommandLineArgs().Contains("--brp-exposure-isolate");
  if(isolateParity){parity=true;tests.Clear();for(int fx=0;fx<=5;fx++){int effect=Mathf.Min(fx,3);tests.Add(new Test{name="isolate"+fx+"-manual",ev=-4,effects=effect,noCull=fx==4,noJitter=fx==5});tests.Add(new Test{name="isolate"+fx+"-taa",ev=4,taa=true,effects=effect,noCull=fx==4,noJitter=fx==5});tests.Add(new Test{name="isolate"+fx+"-auto",mode=ExposureMode.AutomaticHistogram,elevation=2,seconds=6,effects=effect,noCull=fx==4,noJitter=fx==5});}}
  parity|=Environment.GetCommandLineArgs().Contains("--brp-exposure-parity");savedCaptureDelta=Time.captureDeltaTime;if(parity)Time.captureDeltaTime=1f/60;
  dir=Path.Combine(Application.dataPath,parity?"../ValidationParityCycles":isolation?"../Tools/AtmosphereExposureIsolationResults":longSettle?"../Tools/AtmosphereExposureSettleResults":"../ValidationAutoSpecialist");Directory.CreateDirectory(dir);
  if(isolateParity){dir=Path.Combine(Application.dataPath,"../ValidationParityIsolate");Directory.CreateDirectory(dir);}
  File.WriteAllText(Path.Combine(dir,"environment.txt"),"quality="+QualitySettings.GetQualityLevel()+" colorSpace="+QualitySettings.activeColorSpace+" GPU="+SystemInfo.graphicsDeviceName+" API="+SystemInfo.graphicsDeviceType+" projection="+cam.projectionMatrix+" cameraData="+cameraJson+" pipeline="+JsonUtility.ToJson(clone));
  if(diagnostics){tests.RemoveAll(x=>x.name!="isolate1-auto");dir=Path.Combine(Application.dataPath,"../ValidationParityDiagnostics");Directory.CreateDirectory(dir);}
  if(skyOnlyDiagnostic){foreach(var test in tests)test.skyOnly=true;dir=Path.Combine(Application.dataPath,"../ValidationParitySkyOnly");Directory.CreateDirectory(dir);}
  Apply();RenderPipelineManager.endCameraRendering+=End;return Status;}
 static void Apply(){var t=tests[step];typeof(BurtRenderPipelineAsset).GetField("rendererMode",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(clone,(BurtRendererMode)path);typeof(BurtCameraData).GetField("antialiasingMode",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(cd,t.taa?BurtCameraAntialiasingMode.TemporalAntialiasing:BurtCameraAntialiasingMode.None);
  e.enabled.Override(!t.off);e.mode.Override(t.mode);e.manualEV100.Override(t.ev);e.compensation.Override(t.comp);e.calibration.Override(t.cal);e.iso.Override(t.iso);e.shutterTime.Override(1f/60);e.aperture.Override(2.8f);e.autoMinEV100.Override(t.clamp?-1:-8);e.autoMaxEV100.Override(t.clamp?1:12);e.autoSpeedUp.Override(3);e.autoSpeedDown.Override(1);e.autoMiddleGrey.Override(.18f);e.meteringMask.Override(null);
  if(isolateParity){typeof(BurtRenderPipelineAsset).GetField("enableRenderGraphPassCulling",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(clone,!t.noCull);v.jitter.Override(!t.noJitter);}
  typeof(BurtCameraData).GetField("clearColor",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(cd,t.blackClear?Color.black:originalClear);cam.cullingMask=originalMask;for(int i=0;i<renderers.Length;i++)if(renderers[i])renderers[i].enabled=rendererStates[i]&&!t.skyOnly;a.enabled.Override(t.effects>0);a.aerialPerspective.Override(t.effects>=2);v.enabled.Override(t.effects>=3);
  sun.transform.rotation=Quaternion.Euler(t.elevation,195,0);sun.intensity=3;sun.color=Color.white;age=0;start=Time.realtimeSinceStartupAsDouble;Status="Running "+path+"/"+t.name;Save();}
 static void End(ScriptableRenderContext context,Camera c){if(c!=cam)return;try{age++;var t=tests[step];int frames=t.seconds>0?384:128;bool done=parity?age>=frames:t.seconds>0?Time.realtimeSinceStartupAsDouble-start>=t.seconds:age>=120;if(age==1||age==16||age%30==0||done||(parity&&age>frames-32))Capture(t,done);if(done){step++;if(step==tests.Count){step=0;path++;if(path==2){Status="Completed";Stop();return;}}Apply();}}catch(Exception ex){Status="Failed: "+ex;Stop();}}
 static void Capture(Test test,bool png){var old=RenderTexture.active;var t=new Texture2D(rt.width,rt.height,TextureFormat.RGBAFloat,false,true);try{RenderTexture.active=rt;t.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);t.Apply();var colors=t.GetPixels();int bad=0;double sum=0;float max=0;foreach(var c in colors){if(float.IsNaN(c.r)||float.IsInfinity(c.r)||float.IsNaN(c.g)||float.IsInfinity(c.g)||float.IsNaN(c.b)||float.IsInfinity(c.b))bad++;else{sum+=c.r+c.g+c.b;max=Mathf.Max(max,Mathf.Max(c.r,Mathf.Max(c.g,c.b)));}}
  var type=typeof(BurtCameraData).Assembly.GetType("Burt.RenderPipeline.GpuExposureUtility");object[] args={cam,null};bool found=(bool)type.GetMethod("TryGetSnapshot").Invoke(null,args);float current=-1,target=-1;int sampleAge=-1;if(found){object snap=args[1];var st=snap.GetType();if((bool)st.GetField("HasSample").GetValue(snap)){current=(float)st.GetField("CurrentScale").GetValue(snap);target=(float)st.GetField("TargetScale").GetValue(snap);sampleAge=(int)st.GetField("SampleAgeFrames").GetValue(snap);}}
  var all=Resources.FindObjectsOfTypeAll<RenderTexture>();csv.AppendLine(path+","+test.name+","+age+","+(Time.realtimeSinceStartupAsDouble-start)+","+bad+","+sum/(colors.Length*3)+","+max+","+Shader.GetGlobalFloat("_BurtPreExposure")+","+current+","+target+","+sampleAge+","+all.Length+","+all.Sum(x=>UnityEngine.Profiling.Profiler.GetRuntimeMemorySizeLong(x)));File.WriteAllText(Path.Combine(dir,"results.csv"),csv.ToString());
  if(png){var pixels=new Color[colors.Length];for(int i=0;i<colors.Length;i++){var c=colors[i];pixels[i]=new Color(Mathf.LinearToGammaSpace(Mathf.Max(c.r,0)/(1+Mathf.Max(c.r,0))),Mathf.LinearToGammaSpace(Mathf.Max(c.g,0)/(1+Mathf.Max(c.g,0))),Mathf.LinearToGammaSpace(Mathf.Max(c.b,0)/(1+Mathf.Max(c.b,0))));}var outTex=new Texture2D(rt.width,rt.height,TextureFormat.RGB24,false);outTex.SetPixels(pixels);outTex.Apply();File.WriteAllBytes(Path.Combine(dir,path+"-"+test.name+".png"),outTex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(outTex);}
 if(png&&isolateParity)WriteDiagnostics(test);
 }finally{RenderTexture.active=old;UnityEngine.Object.DestroyImmediate(t);}}
 static void WriteDiagnostics(Test test){var sb=new StringBuilder();sb.AppendLine("position="+cam.transform.position+" rotation="+cam.transform.rotation+" atmosphere="+JsonUtility.ToJson(a));var asm=typeof(BurtCameraData).Assembly;foreach(string n in new[]{"BurtAtmosphereUtility","BurtAtmosphereLutUtility"}){var ty=asm.GetType("Burt.RenderPipeline."+n);var method=ty.GetMethod("FormatDebugState",BindingFlags.Public|BindingFlags.Static,null,Type.EmptyTypes,null);if(method!=null)sb.AppendLine(n+"="+method.Invoke(null,null));}foreach(var m in Resources.FindObjectsOfTypeAll<Material>().Where(x=>x.shader&&x.shader.name=="Hidden/BurtRP/AtmosphereScattering")){sb.AppendLine("material="+m.name);foreach(string n in new[]{"_BurtAtmosphereSunDirection","_BurtAtmosphereSunDiskLuminanceAndCosHalfApex","_BurtAtmosphereMainLightColorOuterSpace","_BurtAtmosphereExposureParams","_BurtAtmosphereSkyLuminanceFactor"})sb.AppendLine(n+"="+m.GetVector(n));}
 foreach(var r in Resources.FindObjectsOfTypeAll<RenderTexture>().Where(x=>x.dimension==TextureDimension.Tex2D&&x.name.Contains("Atmosphere")&&x.name.Contains("Lut"))){var old=RenderTexture.active;var tex=new Texture2D(r.width,r.height,TextureFormat.RGBAFloat,false,true);try{RenderTexture.active=r;tex.ReadPixels(new Rect(0,0,r.width,r.height),0,0);tex.Apply();var pixels=tex.GetPixels();double rr=0,gg=0,bb=0;foreach(var px in pixels){rr+=px.r;gg+=px.g;bb+=px.b;}sb.AppendLine(r.name+" "+r.width+"x"+r.height+" mean="+(rr/pixels.Length)+","+(gg/pixels.Length)+","+(bb/pixels.Length));}finally{RenderTexture.active=old;UnityEngine.Object.DestroyImmediate(tex);}}
 AppendLuts(sb);File.WriteAllText(Path.Combine(dir,path+"-"+test.name+"-diagnostics.txt"),sb.ToString());}
 static void AppendLuts(StringBuilder sb){
 var ambient=RenderSettings.ambientProbe;sb.AppendLine("ambient="+RenderSettings.ambientMode+" color="+RenderSettings.ambientLight.ToString("R"));for(int ch=0;ch<3;ch++)for(int i=0;i<9;i++)sb.AppendLine("SH"+ch+"_"+i+"="+ambient[ch,i].ToString("R"));foreach(string n in new[]{"_BurtAmbientSHAr","_BurtAmbientSHAg","_BurtAmbientSHAb","_BurtAmbientColor","_BurtSkyReflectionHDR","_BurtSkyDiffuseCubemapHDR"})sb.AppendLine(n+"="+Shader.GetGlobalVector(n).ToString("R"));
 sb.AppendLine("camera-projection="+cam.projectionMatrix.ToString("R")+" nonjittered="+cam.nonJitteredProjectionMatrix.ToString("R")+" view="+cam.worldToCameraMatrix.ToString("R"));
 foreach(var mesh in Resources.LoadAll<Mesh>("BurtAtmosphereDefaultSkyMesh")){sb.AppendLine("mesh="+mesh.name+" vertices="+mesh.vertexCount+" bounds="+mesh.bounds+" attrs="+string.Join(";",mesh.GetVertexAttributes().Select(x=>x.ToString())));}
 foreach(var m in Resources.FindObjectsOfTypeAll<Material>().Where(x=>x.shader&&x.shader.name=="Hidden/BurtRP/AtmosphereScattering"&&x.GetVector("_BurtAtmosphereSunDirection").sqrMagnitude>.5f)){sb.AppendLine("sky-matrix="+m.GetMatrix("_BurtAtmosphereWorldToSkyViewLocal").ToString("R")+" altitude="+m.GetFloat("_BurtAtmosphereCameraAltitude01").ToString("R"));}
 var ty=typeof(BurtCameraData).Assembly.GetType("Burt.RenderPipeline.BurtDrawAtmospherePass");var fields=ty.GetFields(BindingFlags.Static|BindingFlags.NonPublic);foreach(var m in Resources.FindObjectsOfTypeAll<Material>().Where(x=>x.shader&&x.shader.name=="Hidden/BurtRP/AtmosphereScattering"&&x.GetVector("_BurtAtmosphereSunDirection").sqrMagnitude>.5f)){sb.AppendLine("FULL-MATERIAL");foreach(string array in new[]{"MobilePreparedFloatPropertyIds","MobilePreparedVectorPropertyIds"}){foreach(int id in (int[])ty.GetField(array,BindingFlags.NonPublic|BindingFlags.Static).GetValue(null)){var field=fields.FirstOrDefault(f=>f.FieldType==typeof(int)&&(int)f.GetValue(null)==id);sb.AppendLine((field!=null?field.Name:id.ToString())+"="+(array.Contains("Float")?m.GetFloat(id).ToString("R"):m.GetVector(id).ToString("R")));}}}
 foreach(var r in Resources.FindObjectsOfTypeAll<RenderTexture>().Where(x=>x.dimension==TextureDimension.Tex2D&&x.name.Contains("Atmosphere")&&x.name.Contains("LUT"))){var old=RenderTexture.active;var tex=new Texture2D(r.width,r.height,TextureFormat.RGBAFloat,false,true);try{RenderTexture.active=r;tex.ReadPixels(new Rect(0,0,r.width,r.height),0,0);tex.Apply();var pixels=tex.GetPixels();double rr=0,gg=0,bb=0;foreach(var px in pixels){rr+=px.r;gg+=px.g;bb+=px.b;}sb.AppendLine(r.name+" "+r.width+"x"+r.height+" mean="+(rr/pixels.Length)+","+(gg/pixels.Length)+","+(bb/pixels.Length));}finally{RenderTexture.active=old;UnityEngine.Object.DestroyImmediate(tex);}}
 }
 static void Save(){if(!Status.StartsWith("Running"))Time.captureDeltaTime=savedCaptureDelta;File.WriteAllText(Path.Combine(dir,"status.txt"),Status);}
 static void Guard(){if(!Application.isPlaying||!cam){Status="Interrupted";Stop();}}
 static void Stop(){RenderPipelineManager.endCameraRendering-=End;if(cam){cam.targetTexture=null;cam.cullingMask=originalMask;JsonUtility.FromJsonOverwrite(cameraJson,cd);}if(rt){rt.Release();UnityEngine.Object.DestroyImmediate(rt);}sun.transform.rotation=sunRot;sun.intensity=lightIntensity;sun.color=lightColor;for(int i=0;i<lights.Length;i++)if(lights[i])lights[i].enabled=states[i];if(renderers!=null)for(int i=0;i<renderers.Length;i++)if(renderers[i])renderers[i].enabled=rendererStates[i];foreach(var pair in saved)JsonUtility.FromJsonOverwrite(pair.Value,pair.Key);foreach(var component in added){profile.components.Remove(component);UnityEngine.Object.DestroyImmediate(component);}QualitySettings.renderPipeline=original;UnityEngine.Object.DestroyImmediate(clone);Application.runInBackground=bg;Save();if(!Application.isEditor)Application.Quit(Status=="Completed"?0:2);}
}
public sealed class BurtExposureValidationDriver : MonoBehaviour
{
    private bool started;
    private double startedAt;
    private void Update()
    {
        try
        {
            if (!started && Time.frameCount > 8)
            {
                started = true;
                startedAt = Time.realtimeSinceStartupAsDouble;
                Debug.Log("Exposure validation: " + BurtExposurePlayerValidation.Start());
            }
            if (started) BurtExposurePlayerValidation.Heartbeat();
            if (started && Time.realtimeSinceStartupAsDouble - startedAt > 600)
            {
                Debug.LogError("Exposure validation timed out: " + BurtExposurePlayerValidation.Status);
                Application.Quit(2);
            }
        }
        catch (Exception ex) { Debug.LogException(ex); Application.Quit(2); }
    }
}
#endif
