// Lightweight shading-debug include for unlit material shaders.
#ifndef BURT_SHADING_DEBUG_UNLIT_INCLUDED
#define BURT_SHADING_DEBUG_UNLIT_INCLUDED

#if defined(BURT_SHADING_DEBUG) && !defined(BURT_ENABLE_SHADING_DEBUG)
#define BURT_ENABLE_SHADING_DEBUG 1
#endif

#if defined(BURT_ENABLE_SHADING_DEBUG) && BURT_ENABLE_SHADING_DEBUG
#define BURT_FORWARD_SINGLE_SHADING_MODEL 1
#define BURT_MATERIAL_SHADING_MODEL_DEFAULT_LIT 1
#define BURT_SHADING_DEBUG_INCLUDE_SHADOW 0
#define BURT_SHADING_DEBUG_INCLUDE_ADDITIONAL_LIGHTS 0
#define BURT_SHADING_DEBUG_MATERIAL_INCLUDE_CORE 1
#define BURT_SHADING_DEBUG_MATERIAL_INCLUDE_BRDF 0
#define BURT_SHADING_DEBUG_MATERIAL_INCLUDE_LIGHTING 0
#define BURT_SHADING_DEBUG_MATERIAL_INCLUDE_TRANSMISSION 0
#define BURT_SHADING_DEBUG_MATERIAL_INCLUDE_HAIR 0
#define BURT_SHADING_DEBUG_MATERIAL_INCLUDE_SHADOW 0
#include "Assets/BurtRP/Runtime/Shaders/ShaderLibrary/Debug/BurtShadingDebug.hlsl"
#endif

#endif // BURT_SHADING_DEBUG_UNLIT_INCLUDED
