// BurtRP shading-debug mode ids and C# driven global controls.
#ifndef BURT_SHADING_DEBUG_MODES_INCLUDED
#define BURT_SHADING_DEBUG_MODES_INCLUDED

float _BurtShadingDebugMode;
float _BurtShadingDebugEnabled;

// Material inputs.
#define BURT_SHADING_DEBUG_MODE_ALBEDO (100.0f)
#define BURT_SHADING_DEBUG_MODE_NORMAL_WS (101.0f)
#define BURT_SHADING_DEBUG_MODE_SMOOTHNESS (102.0f)
#define BURT_SHADING_DEBUG_MODE_METALLIC (103.0f)
#define BURT_SHADING_DEBUG_MODE_OCCLUSION (104.0f)
#define BURT_SHADING_DEBUG_MODE_REFLECTANCE (105.0f)
#define BURT_SHADING_DEBUG_MODE_ROUGHNESS (106.0f)
#define BURT_SHADING_DEBUG_MODE_SPECULAR_AA_ROUGHNESS (107.0f)
#define BURT_SHADING_DEBUG_MODE_SPECULAR_ENERGY_COMPENSATION (108.0f)
#define BURT_SHADING_DEBUG_MODE_SPECULAR_OCCLUSION (109.0f)
#define BURT_SHADING_DEBUG_MODE_ENERGY_PRESERVATION (110.0f)
#define BURT_SHADING_DEBUG_MODE_INDIRECT_SPECULAR_ENERGY_COMPENSATION (111.0f)
#define BURT_SHADING_DEBUG_MODE_DIFFUSE_COLOR (112.0f)
#define BURT_SHADING_DEBUG_MODE_HEIGHT (113.0f)
#define BURT_SHADING_DEBUG_MODE_PRESKIN_POSITION (114.0f)

// Direct BRDF and specular filtering.
#define BURT_SHADING_DEBUG_MODE_DIRECT_BRDF_D (115.0f)
#define BURT_SHADING_DEBUG_MODE_DIRECT_BRDF_VISIBILITY (116.0f)
#define BURT_SHADING_DEBUG_MODE_DIRECT_BRDF_FRESNEL (117.0f)
#define BURT_SHADING_DEBUG_MODE_DIRECT_DIFFUSE_LOBE (118.0f)
#define BURT_SHADING_DEBUG_MODE_DIRECT_DIFFUSE_BRDF (119.0f)
#define BURT_SHADING_DEBUG_MODE_DIRECT_SPECULAR_BRDF (120.0f)
#define BURT_SHADING_DEBUG_MODE_SPECULAR_AA_NORMAL_VARIANCE (121.0f)
#define BURT_SHADING_DEBUG_MODE_SPECULAR_AA_ROUGHNESS_DELTA (122.0f)
#define BURT_SHADING_DEBUG_MODE_INDIRECT_SPECULAR_DFG (123.0f)
#define BURT_SHADING_DEBUG_MODE_INDIRECT_SPECULAR_ENV_BRDF (124.0f)

// Subsurface and transmission.
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_PROFILE_ID (125.0f)
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_TRANSMISSION (126.0f)
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_KERNEL_WEIGHT (127.0f)
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_INDIRECT (128.0f)
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_DIRECT_TRANSMISSION (129.0f)

// GBuffer decode views.
#define BURT_SHADING_DEBUG_MODE_GBUFFER_BASE_COLOR (130.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_NORMAL_WS (131.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_METALLIC (132.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_SMOOTHNESS (133.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_OCCLUSION (134.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_REFLECTANCE (135.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_ROUGHNESS (136.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_DIFFUSE_COLOR (137.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_CLEAR_COAT_MASK (141.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_SUBSURFACE_STRENGTH (142.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_CLEAR_COAT_NORMAL_WS (143.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_CLEAR_COAT_ROUGHNESS (144.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_ANISOTROPY (145.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_TANGENT_WS (146.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_SUBSURFACE_THICKNESS (147.0f)
#define BURT_SHADING_DEBUG_MODE_GBUFFER_SUBSURFACE_PROFILE_INDEX (148.0f)

// Subsurface transmission internals.
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_TRANSMISSION_BRDF (149.0f)
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_TRANSMISSION_SHADOW (150.0f)
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_TRANSMISSION_PHASE (151.0f)
#define BURT_SHADING_DEBUG_MODE_SUBSURFACE_TRANSMISSION_THICKNESS (152.0f)

// Foliage and grass transmission.
#define BURT_SHADING_DEBUG_MODE_GBUFFER_FOLIAGE_SCREEN_SPACE_SHADOW_INTENSITY (158.0f)
#define BURT_SHADING_DEBUG_MODE_FOLIAGE_TRANSMISSION (161.0f)
#define BURT_SHADING_DEBUG_MODE_FOLIAGE_DIRECT_TRANSMISSION (162.0f)
#define BURT_SHADING_DEBUG_MODE_FOLIAGE_TRANSMISSION_BRDF (163.0f)
#define BURT_SHADING_DEBUG_MODE_FOLIAGE_TRANSMISSION_SHADOW (164.0f)
#define BURT_SHADING_DEBUG_MODE_FOLIAGE_SPECULAR_BRDF (165.0f)
#define BURT_SHADING_DEBUG_MODE_GRASS_TRANSMISSION (170.0f)
#define BURT_SHADING_DEBUG_MODE_GRASS_DIRECT_TRANSMISSION (171.0f)
#define BURT_SHADING_DEBUG_MODE_GRASS_TRANSMISSION_BRDF (172.0f)
#define BURT_SHADING_DEBUG_MODE_GRASS_TRANSMISSION_SHADOW (173.0f)
#define BURT_SHADING_DEBUG_MODE_GRASS_SPECULAR_BRDF (174.0f)

// Lighting.
#define BURT_SHADING_DEBUG_MODE_DETAIL_LIGHTING (200.0f)
#define BURT_SHADING_DEBUG_MODE_INDIRECT_LIGHTING (201.0f)
#define BURT_SHADING_DEBUG_MODE_DIRECT_DIFFUSE (202.0f)
#define BURT_SHADING_DEBUG_MODE_DIRECT_SPECULAR (203.0f)
#define BURT_SHADING_DEBUG_MODE_INDIRECT_DIFFUSE (204.0f)
#define BURT_SHADING_DEBUG_MODE_INDIRECT_SPECULAR (205.0f)
#define BURT_SHADING_DEBUG_MODE_SHADOW_ATTENUATION (206.0f)
#define BURT_SHADING_DEBUG_MODE_AMBIENT_OCCLUSION (207.0f)
#define BURT_SHADING_DEBUG_MODE_EMISSION (208.0f)
#define BURT_SHADING_DEBUG_MODE_FINAL_LIGHTING (209.0f)
#define BURT_SHADING_DEBUG_MODE_HAIR_PRIMARY_LOBE (210.0f)
#define BURT_SHADING_DEBUG_MODE_HAIR_SECONDARY_LOBE (211.0f)
#define BURT_SHADING_DEBUG_MODE_HAIR_TRANSMISSION_LOBE (212.0f)
#define BURT_SHADING_DEBUG_MODE_HAIR_SCATTER (213.0f)
#define BURT_SHADING_DEBUG_MODE_SHADOW_CASCADE_INDEX (214.0f)
#define BURT_SHADING_DEBUG_MODE_SHADOW_CASCADE_BLEND (215.0f)
#define BURT_SHADING_DEBUG_MODE_SHADOW_DISTANCE_FADE (216.0f)
#define BURT_SHADING_DEBUG_MODE_SHADOW_PCSS_RADIUS (217.0f)
#define BURT_SHADING_DEBUG_MODE_SHADOW_RECEIVER_DEPTH_DELTA (218.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_LIGHTING (219.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_DIFFUSE (220.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_SPECULAR (221.0f)
#define BURT_SHADING_DEBUG_MODE_HAIR_ADDITIONAL_LIGHTING (222.0f)
#define BURT_SHADING_DEBUG_MODE_SHADOW_PCSS_BLOCKER_FRACTION (225.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_SHADOW_ATTENUATION (226.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_LIGHTING_UNSHADOWED (227.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_SHADOW_FACE (228.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_SHADOW_UV (229.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_SHADOW_DEPTH (230.0f)
#define BURT_SHADING_DEBUG_MODE_ADDITIONAL_SHADOW_DEPTH_DELTA (231.0f)
#define BURT_SHADING_DEBUG_MODE_MAIN_LIGHT_SHADOW_RECEIVER_DEPTH (234.0f)
#define BURT_SHADING_DEBUG_MODE_MAIN_LIGHT_SHADOW_RAW_DEPTH (235.0f)
#define BURT_SHADING_DEBUG_MODE_MAIN_LIGHT_SHADOW_COMPARE (236.0f)
#define BURT_SHADING_DEBUG_MODE_MAIN_LIGHT_SHADOW_PROJECTION_VALIDITY (237.0f)

// Per-object shadow debug.
#define BURT_SHADING_DEBUG_MODE_PER_OBJECT_SHADOW_OBJECT_INDEX (476.0f)
#define BURT_SHADING_DEBUG_MODE_PER_OBJECT_SHADOW_SLICE (477.0f)
#define BURT_SHADING_DEBUG_MODE_PER_OBJECT_SHADOW_UV (478.0f)
#define BURT_SHADING_DEBUG_MODE_PER_OBJECT_SHADOW_DEPTH (479.0f)
#define BURT_SHADING_DEBUG_MODE_PER_OBJECT_SHADOW_COMPARE (480.0f)
#define BURT_SHADING_DEBUG_MODE_PER_OBJECT_SHADOW_TRANSMISSION_DEPTH (481.0f)
#define BURT_SHADING_DEBUG_MODE_PER_OBJECT_SHADOW_TRANSMISSION_THICKNESS (493.0f)

// GI probe and global debug helpers.
#define BURT_SHADING_DEBUG_MODE_GI_PROBE_IRRADIANCE (503.0f)
#define BURT_SHADING_DEBUG_MODE_GI_PROBE_VALIDITY (504.0f)
#define BURT_SHADING_DEBUG_MODE_GI_PROBE_SKY_VISIBILITY (505.0f)
#define BURT_SHADING_DEBUG_MODE_SCREEN_SPACE_GLOBAL_ILLUMINATION_SCENE_VOXEL_OCCUPANCY (506.0f)
#define BURT_SHADING_DEBUG_MODE_GI_PROBE_RUNTIME_INFO (507.0f)

#define BURT_SHADING_DEBUG_SUBSURFACE_PROFILE_SLOT_COUNT (8.0f)

#endif // BURT_SHADING_DEBUG_MODES_INCLUDED
